apps/front/models.py
from exts import db
import shortuuid
from werkzeug.security import  generate_password_hash,check_password_hash
import enum
from datetime import datetime

class GenderEnum(enum.Enum):
    MALE = 1
    FEMALE = 2
    SECRET = 3
    UNKNOW = 4

# 为了隐藏用户的数量的显示，不要使用自动增长，应该使用随机字符串
# unique:保持唯一
class FrontUser(db.Model):
    __tablename__ = 'front_user'
    id = db.Column(db.String(100),primary_key=True,default=shortuuid.uuid)
    telephone = db.Column(db.String(11),nullable=False,unique=True)
    username = db.Column(db.String(50),nullable=False)
    _password = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(50),unique=True)
    realname = db.Column(db.String(50))
    avatar = db.Column(db.String(100))
    signature = db.Column(db.String(100))
    gender = db.Column(db.Enum(GenderEnum),default=GenderEnum.UNKNOW)
    join_time = db.Column(db.DateTime,default=datetime.now)

    def __init__(self,*args,**kwargs):
        if "password" in kwargs:
            self.password = kwargs.get('password')
            kwargs.pop("password")
        super(FrontUser,self).__init__(*args,**kwargs)

    # 将password函数定义为属性
    @property
    def password(self):
        return self._password

    # 通过werkzeug的内置has函数进行加密和解密，判断
    @password.setter
    def password(self,newpwd):
        self._password = generate_password_hash(newpwd)

    def check_password(self,rawpwd):
        return check_password_hash(self._password,rawpwd)

apps/front/forms.py
from ..forms import  BaseForm
from wtforms import StringField,IntegerField
from wtforms.validators import Regexp,EqualTo,ValidationError,InputRequired
from utils import zlcache

class SignupForm(BaseForm):
    telephone = StringField(validators=[Regexp(r"1[345789]\d{9}",message="请输入正确格式的手机号码")])
    sms_captcha = StringField(validators=[Regexp(r"\w{4}",message="请输入正确格式的短信验证码")])
    username = StringField(validators=[Regexp(r".{2,20}",message="请输入正确格式的用户名")])
    password1 = StringField(validators=[Regexp(r"[0-9a-zA-Z]{6,20}",message="请输入正确格式的密码")])
    password2 = StringField(validators=[EqualTo("password1",message="两次输入的密码不一致")])
    graph_captcha = StringField(validators=[Regexp(r"\w{4}",message="请输入正确格式的图形验证码")])
    # print(password1,password2)
    def validate_sms_captcha(self,field):
        sms_captcha = field.data
        telephone = self.telephone.data
        sms_captcha_mem = zlcache.get(telephone)
        if not sms_captcha_mem or sms_captcha_mem.lower() != sms_captcha.lower():
            raise ValidationError(message="短信验证码错误")

    def validate_graph_captcha(self,field):
        try:
            graph_captcha = field.data
            graph_captcha_mem = zlcache.get(graph_captcha)
            if not graph_captcha_mem:
                raise ValidationError(message="图形验证码错误")
        except:
            raise ValidationError(message="图形验证码错误")


class SigninForm(BaseForm):
    telephone = StringField(validators=[Regexp(r"1[345789]\d{9}",message="请输入正确格式的手机号码")])
    password = StringField(validators=[Regexp(r"[0-9a-zA-Z]{6,20}",message="请输入正确格式的密码")])
    remeber = StringField()


class AddPostForm(BaseForm):
    title = StringField(validators=[InputRequired(message="请输入标题！")])
    content = StringField(validators=[InputRequired(message="请输入内容！")])
    board_id = IntegerField(validators=[InputRequired(message="请输入板块id！")])


class AddCommentForm(BaseForm):
    content = StringField(validators=[InputRequired(message="请输入评论内容")])
    post_id = IntegerField(validators=[InputRequired(message="请输入帖子id")])

apps/common/views.py
from flask import Blueprint,request,make_response,jsonify
from utils.sms import demo_sms_send
from utils import restful,zlcache
from utils.captcha import Captcha
from .forms import SMSCaptchaForm
from io import BytesIO
from utils.captcha import Captcha
import qiniu
import config
from tasks import send_sms_captcha

# 注意设置url前缀的时候一定要加入'/'
bp = Blueprint("common",__name__,url_prefix='/c')

# @bp.route('/sms_captcha/')
# def sms_captcha():
#     telephone = request.args.get('telephone')
#     if not telephone:
#         return restful.params_error(message="请传入手机号码")
#     # result = alidayu.send_sms("+86-188923326060",code="abcd")
#     captcha = Captcha.gene_text(4)
#     if demo_sms_send.send_api(telephone,code=captcha):
#         return restful.success()
#     else:
#         return restful.params_error(message="短信验证码发送失败！")


@bp.route('/sms_captcha/',methods=['POST'])
def sms_captcha():
    # telephone
    # timestamp
    # md5(ts+telephone+salt)
    form = SMSCaptchaForm(request.form)
    if form.validate():
        telephone = form.telephone.data
        captcha = Captcha.gene_text(4)
        print("发送的短信验证码是:",captcha)
        send_sms_captcha(telephone=telephone,captcha=captcha)
        return restful.success()
        # if demo_sms_send.send_api(telephone,code=captcha):
        #     # 利用memcached进行缓存
        #     zlcache.set(telephone,captcha)
        #     return restful.success()
        # else:
        #     return restful.params_error(message="短信验证码发送失败！")
    else:
        return restful.params_error(message="参数错误")


@bp.route('/captcha/')
def graph_captcha():
    try:
        # 获取验证码
        text,image = Captcha.gene_graph_captcha()
        zlcache.set(text.lower(),text.lower())
        # BytesIO,字节流
        # 获取图像，需要存入二进制流中
        out = BytesIO()
        # 保存在流中，并指定格式为png
        image.save(out,'png')
        out.seek(0)
        # response对象
        resp = make_response(out.read())
        resp.content_type = 'image/png'
    except:
        return graph_captcha()
    return resp


@bp.route('/uptoken/')
def uptoken():
    # AK
    access_key = config.UEDITOR_QINIU_ACCESS_KEY
    # SK
    secret_key = config.UEDITOR_QINIU_SECRET_KEY
    # 验证
    q = qiniu.Auth(access_key,secret_key)
    # 储存空间名字
    bucket = config.UEDITOR_QINIU_BUCKET_NAME
    token = q.upload_token(bucket)
    return jsonify({"uptoken":token})

apps/front/__init__.py
from .views import  bp
from . import hooks

apps/front/views.py
from flask import (
    Blueprint,
    views,
    render_template,
    request,
    session,
    url_for,
    g,
    abort
)
from .forms import SignupForm,SigninForm,AddPostForm,AddCommentForm
from utils import restful,safeutils
from .models import FrontUser
from ..models import BoardModel,BannerModel,PostModel,CommentModel,HighlightPostModel,LikePostModel
from exts import db
import config
from .decorators import login_required
# from exts import alidayu
from flask_paginate import Pagination,get_page_parameter
from sqlalchemy.sql import func

bp = Blueprint("front",__name__)

@bp.route('/')
def index():
    sort = request.args.get("st",type=int,default=1) # 排序
    board_id = request.args.get("board_id",type=int,default=None)
    boards = BoardModel.query.all()
    banners = BannerModel.query.order_by(BannerModel.priority.desc(),BannerModel.create_time.desc()).limit(4)
    # posts = PostModel.query.all()
    page = request.args.get(get_page_parameter(),type=int,default=1)
    offset = (page-1) * config.PER_PAGE
    count = offset + config.PER_PAGE
    # 从第几条开始显示第end条数据
    # posts = PostModel.query.slice(offset,count)
    posts = None
    total = 0
    query_obj = None

    if sort == 1:
        # 最新
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 2:
        # 按加精时间倒序排序
        # 两个表连接查询需要使用db.session()
        query_obj = db.session.query(PostModel).outerjoin(HighlightPostModel).order_by(HighlightPostModel.create_time.desc(),PostModel.create_time.desc())
    elif sort == 3:
        # 按照点赞数量排序
        query_obj = db.session.query(PostModel).outerjoin(LikePostModel).order_by(LikePostModel.like_num.desc(),PostModel.create_time.desc())
    elif sort == 4:
        query_obj = db.session.query(PostModel).outerjoin(CommentModel).group_by(PostModel.id).order_by(func.count(CommentModel.id).desc(),PostModel.create_time.desc())

    if board_id:
        # 按照版块筛选
        query_obj = PostModel.query.filter(PostModel.board_id==board_id)
        posts = query_obj.slice(offset,count)
        total = query_obj.count()
    else:
        posts = query_obj.slice(offset,count)
        total = query_obj.count()
    # 传入页数参数，数据的总条数
    pagination = Pagination(bs_version=3,page=page,total=total,outer_window=0,inner_window=2)
    context = {
        "boards":boards,
        "banners":banners,
        'posts':posts,
        'pagination':pagination,
        'current_board':board_id,
        'current_sort':sort,
        'like_obj':db.session.query(LikePostModel).outerjoin(PostModel),
    }
    return render_template("front/index.html",**context)

@bp.route('/<name>/<post_id>/')
def post_detail(name,post_id):
    post = PostModel.query.get(post_id)
    like = db.session.query(LikePostModel).outerjoin(PostModel).filter(PostModel.id == post_id).first()
    if not post:
        abort(404)
    return render_template('front/pdetail.html',post=post,like=like)

@bp.route('/acomment/',methods=["POST"])
@login_required
def add_comment():
    form = AddCommentForm(request.form)
    if form.validate():
        content = form.content.data
        # 通过帖子id，判断是否有当前帖子
        post_id = form.post_id.data
        post = PostModel.query.get(post_id)
        if post:
            comment = CommentModel(content=content)
            comment.post = post
            comment.author = g.front_user
            db.session.add(comment)
            db.session.commit()
            return restful.success()
        else:
            return  restful.params_error("没有这篇帖子！")
    else:
        return restful.params_error(form.get_error())

@bp.route('/apost/',methods=['GET','POST'])
@login_required
def apost():
    if request.method == "GET":
        boards = BoardModel.query.all()
        return render_template('front/apost.html',boards=boards)
    else:
        form = AddPostForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            board_id = form.board_id.data
            board = BoardModel.query.get(board_id)
            if not board:
                return restful.params_error(message="没有这个模块！")
            post = PostModel(title=title,content=content)
            post.board = board
            post.author = g.front_user
            db.session.add(post)
            db.session.commit()
            return  restful.success()
        else:
            return restful.params_error(message=form.get_error())

@bp.route('/alike/')
def add_like():
    post_id = request.args.get("post_id")
    post = PostModel.query.get(post_id)
    if not post:
        return restful.params_error("没有这篇帖子！")
    like = db.session.query(LikePostModel).outerjoin(PostModel).filter(PostModel.id==post_id).first()
    if like:
        like_num = like.like_num
    else:
        like = LikePostModel(like_num=0)
        like.post = post
        like_num = 0
    like_num = like_num+1
    print(like_num)
    like.like_num = like_num
    db.session.commit()
    return restful.success()

class SignupView(views.MethodView):

    def get(self):
        return_to = request.referrer
        print(return_to)
        if return_to and return_to != request.url and safeutils.is_safe_url(return_to):
            return render_template('front/signup.html',return_to=return_to)
        else:
            return render_template('front/signup.html')

    def post(self):
        form = SignupForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            username = form.username.data
            password = form.password1.data
            user = FrontUser(telephone=telephone,username=username,password=password)
            db.session.add(user)
            db.session.commit()
            return restful.success()
        else:
            # print(form.get_error())
            return restful.params_error(message=form.get_error())

class SigninView(views.MethodView):

    def get(self):
        return_to = request.referrer
        if return_to and return_to != request.url and return_to != url_for("front.signup") and safeutils.is_safe_url(return_to):
             return render_template("front/signin.html",return_to=return_to)
        else:
             return render_template('front/signin.html')

    def post(self):
        form = SigninForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            password = form.password.data
            remember = form.remeber.data
            # 检索是否拥有这个账号
            user = FrontUser.query.filter_by(telephone=telephone).first()
            if user and user.check_password(password):
                session[config.FRONT_USER_ID] = user.id
                if remember:
                    session.permanent = True
                return restful.success()
            else:
                return restful.params_error(message="手机号码或者密码错误")
        else:
            return restful.params_error(message=form.get_error())


bp.add_url_rule(rule='/signup/',view_func=SignupView.as_view('signup'))
bp.add_url_rule(rule='/signin/',view_func=SigninView.as_view('signin'))

templates/front/apost.html
{% extends "front/base.html" %}
{% from "common/_macros.html" import static%}

{% block title %}
    发布帖子
{% endblock %}

{% block head %}
    <script src="{{ static("ueditor/ueditor.config.js") }}"></script>
    <script src="{{ static("ueditor/ueditor.all.min.js") }}"></script>
    <script src="{{ static("front/js/apost.js") }}"></script>
{% endblock %}

{% block body %}
    <form action="" method="post" autocomplete="off">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon">标题</span>
                <input type="text" class="form-control" name="title">
            </div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon">版块</span>
                    <select name="board_id" class="form-control">
                        {% for board in boards %}
                            <option value="{{ board.id }}">{{ board.name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>
        <div class="form-group">
           <script id="editor" type="text/plain" style="height: 600px"></script>
        </div>
        <div class="form-group">
            <a href="{{ url_for("front.apost") }}" class="btn btn-danger" id="submit-btn">发布帖子</a>
        </div>
    </form>
{% endblock %}

templates/front/base.html
{% from "common/_macros.html" import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% include "common/_heads.html" %}
    <link rel="stylesheet" href="{{ static('front/css/base.css') }}"/>
    <title>
        {% block title %}{% endblock %}
    </title>
    {% block head %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">论坛</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/">首页<span class="sr-only">(current)</span></a></li>
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="请输入关键字">
                </div>
                <button type="submit" class="btn btn-default">搜索</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if g.front_user %}
                    <span id="login-tag" data-is-login="1" style="display: none"></span>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" type="button" id="dropdownMenu1"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                            {{ g.front_user.username }}
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            <li><a href="#">个人中心</a></li>
                            <li><a href="#">设置</a></li>
                            <li><a href="#">注销</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{{ url_for("front.signin") }}">登陆</a></li>
                    <li><a href="{{ url_for("front.signup") }}">注册</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="main-container">
    {% block  body %}

    {% endblock %}
</div>
</body>
</html>

templates/front/index.html
{% extends "front/base.html" %}
{% from "common/_macros.html" import static %}

{% block title %}
    Tokimeki论坛
{% endblock %}


{% block head %}
    <link rel="stylesheet" href="{{ static("front/css/index.css") }}"/>
{% endblock %}


{% block body %}
    <div class="lg-container">
        <div id="carousel-example-generic" class="carousel slide index-banner" data-ride="carousel">
            <!-- 指示器*小圆点 -->
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                <li data-target="#carousel-example-generic" data-slide-to="3"></li>
            </ol>

            <!-- 轮播图 -->
            <div class="carousel-inner" role="listbox">
                {% for banner in banners %}
                    {% if loop.first %}
                        <div class="item active">
                    {% else %}
                        <div class="item">
                    {% endif %}
                <a href="{{ banner.link_url }}">
                    <img src="{{ banner.image_url }}" alt="...">
                </a>
                </div>
                {% endfor %}
                </div>

                <!-- 左右切换的按钮 -->
                <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="post-group">
                <ul class="nav nav-pills">
                    {% if current_sort == 1 %}
                        <li role="presentation" class="active"><a href="{{ url_for("front.index",st=1,board_id=current_board) }}">最新</a></li>
                    {% else %}
                        <li role="presentation"><a href="{{ url_for("front.index",st=1,board_id=current_board) }}">最新</a></li>
                    {% endif %}
                    {% if current_sort == 2 %}
                        <li role="presentation" class="active"><a href="{{ url_for("front.index",st=2,board_id=current_board) }}">精华帖子</a></li>
                    {% else %}
                        <li role="presentation"><a href="{{ url_for("front.index",st=2,board_id=current_board) }}">精华帖子</a></li>
                    {% endif %}
                    {% if current_sort == 3 %}
                        <li role="presentation" class="active"><a href="{{ url_for("front.index",st=3,board_id=current_board) }}">点赞最多</a></li>
                    {% else %}
                        <li role="presentation"><a href="{{ url_for("front.index",st=3,board_id=current_board) }}">点赞最多</a></li>
                    {% endif %}
                    {% if current_sort == 4 %}
                        <li role="presentation" class="active"><a href="{{ url_for("front.index",st=4,board_id=current_board) }}">评论最多</a></li>
                    {% else %}
                        <li role="presentation"><a href="{{ url_for("front.index",st=4,board_id=current_board) }}">评论最多</a></li>
                    {% endif %}

                </ul>

                <ul class="post-list-group">
                    {% for post in posts %}
                        <li>
                            <div class="author-avatar-group">
                                <img src="{{ post.author.avatar or url_for('static',filename="common/images/logo.png") }}"
                                     alt="">
                            </div>
                            <div class="post-info-group">
                                <p class="post-title">
                                    <a href="{{ url_for("front.post_detail",post_id=post.id,name=post.author.username) }}">{{ post.title }}</a>

                                    {% if post.highlight %}
                                        <span class="label label-danger">精华帖</span>
                                    {% endif %}

                                </p>
                                <p class="post-info">
                                    <span>作者:{{ post.author.username }}</span>
                                    <span>发表时间:{{ post.create_time }}</span>
                                    <span>评论:{{ post.comments|length }}</span>
                                    <span>阅读:0</span>
                                    {% if post.like %}
                                        <span>点赞数:{{ post.like[0].like_num }}</span>
                                    {% else %}
                                        <span>点赞数:{{ 0 }}</span>
                                    {% endif %}
                                </p>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
                <div style="text-align: center">
                    {{ pagination.links }}
                </div>
            </div>
        </div>
        <div class="sm-container">
            <div style="padding-bottom: 10px;">
                <a href="{{ url_for("front.apost") }}" class="btn btn-warning btn-block">发表帖子</a>
            </div>
            <div class="list-group">
                {% if current_board %}
                    <a href="/" class="list-group-item">所有版块</a>
                {% else %}
                    <a href="/" class="list-group-item active">所有版块</a>
                {% endif %}
                {% for board in boards %}
                    {% if board.id == current_board %}
                        <a href="{{ url_for("front.index",board_id = board.id) }}"
                           class="list-group-item active">{{ board.name }}</a>
                    {% else %}
                        <a href="{{ url_for("front.index",board_id = board.id) }}"
                           class="list-group-item">{{ board.name }}</a>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/front/pdetail.html
{% extends "front/base.html" %}
{% from "common/_macros.html" import static %}
{% block title %}
    {{ post.title }}
{% endblock %}

{% block head %}
    <script src="{{ static("ueditor/ueditor.config.js") }}"></script>
    <script src="{{ static("ueditor/ueditor.all.min.js") }}"></script>
    <script src="{{ static("front/js/pdetail.js") }}"></script>
    <link rel="stylesheet" href="{{ url_for('static',filename="front/css/pdetail.css") }}">
{% endblock %}

{% block body %}
    <div class="lg-container" comment-txt>
        <div class="post-container">
            <h2>{{ post.title }}</h2>
            <p class="post-info-group">
                <span>发表时间：{{ post.create_time }}</span>
                <span>作者：{{ post.author.username }}</span>
                <span>所属板块：{{ post.board.name }}</span>
                <span>阅读数：0</span>
                <span>评论数：{{ post.comments|length }}</span>
            </p>
            <article class="post-content" id="post-content" data-id="{{ post.id }}">
                {{ post.content|safe }}
            </article>
            <div class="like-group">
                <span class="glyphicon glyphicon-thumbs-up like-star" aria-hidden="true" data-id="{{ post.id }}"></span>
                <span class="glyphicon-class">喜欢 {{ like.like_num or 0}}</span>
            </div>
        </div>

        {% if post.comments %}
            <div class="comment-group">
                <h3>评论列表</h3>
                <ul class="comment-list-group">
                    {% for comment in post.comments %}
                        <li>
                            <div class="avatar-group">
                                <img src="{{ comment.author.avatar or static("common/images/logo.png") }}" alt="">
                            </div>
                            <div class="comment-content">
                                <p class="author-info">
                                    <span>{{ comment.author.username }}</span>
                                    <span>{{ comment.create_time }}</span>
                                </p>
                                <p class="bg-warning">
                                    {{ comment.content|safe }}
                                </p>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        <div class="add-comment-group">
            <h3>发表评论</h3>
            <script id="editor" type="text/plain" style="height:100px;"></script>
            <div class="comment-btn-group">
                <button class="btn btn-primary" id="comment-btn"> 发表评论</button>
            </div>
        </div>
    </div>
    </div>
    <div class="sm-container"> < /div>
{% endblock %}

templates/front/signbase.html
{% from "common/_macros.html" import static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{% block title %}{% endblock %}</title>
    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="http://cdn.bootcss.com/blueimp-md5/2.10.0/js/md5.min.js"></script>
    <script src="{{ static('common/zlparam.js') }}"></script>
     <script src="{{ static("common/zlajax.js") }}"></script>
     <link rel="stylesheet" href="{{ static("common/sweetalert/sweetalert.css") }}">
    <script src="{{ static("common/sweetalert/sweetalert.min.js") }}"></script>
    <script src="{{ static("common/sweetalert/zlalert.js") }}"></script>
    <link href="{{ static("front/css/signbase.css") }}" rel="stylesheet">
    {% block head %}

    {% endblock %}
</head>
<body>
    <div class="outer-box" style="margin: 120px auto;">
        <div class="logo-box">
            <a href="/">
                <img src="{{ static("common/images/logo.png") }}"/>
            </a>
        </div>
        <h2 class="page-title">
            {% block h2_block %}{% endblock %}
        </h2>

        <div class="sign-box">
            {% block signbox %}
            
            {% endblock %}
        </div>
    </div>
</body>
</html>

templates/front/signin.html
{% extends 'front/signbase.html' %}
{% from "common/_macros.html" import static %}

{% block title %}
    论坛账号登录
{% endblock %}

{% block head %}
    <style>
        .reset-link{
            float: right;
        }
    </style>
    <script src="{{ static("front/js/signin.js") }}"></script>
{% endblock %}

{% block h2_block %}
    论坛账号登录
{% endblock %}

{% block signbox %}
    <div class="form-group">
        <input type="text" name="telephone" class="form-control" placeholder="手机号码" autocomplete="off">
    </div>
    <div class="form-group">
        <input type="password" name="password" class="form-control" placeholder="密码" autocomplete="off">
    </div>
    <div class="checkbox">
        <label>
            <input type="checkbox" name="remember" value="1"/>记住我
        </label>
    </div>
    <div class="form-group">
        <button id="submit-btn" class="btn btn-warning btn-block">
            立即登录
        </button>
    </div>
    <div class="form-group">
        <a href="{{ url_for("front.signup") }}" class="signup-link">没有账号?立即注册</a>
        <a href="#" class="reset-link">忘记密码?</a>
    </div>
{% endblock %}

templates/front/signup.html
{% extends 'front/signbase.html' %}
{% from "common/_macros.html" import static %}

{% block title %}
    论坛账号注册
{% endblock %}

{% block head %}
    <script src="{{ static("front/js/signup.js") }}"></script>
{% endblock %}

{% block h2_block %}
    论坛账号注册
{% endblock %}

{% block signbox %}
    <div class="form-group" style="margin:0 auto;">
                <div class="input-group">
                    <input type="text" name="telephone" class="form-control" placeholder="手机号码">
                    <span class="input-group-btn">
                        <button  id="sms-captcha-btn" class="btn btn-default">
                            发送验证码
                        </button>
                    </span>
                </div>
            </div>
            <div class="form-group">
                <input type="text" name="sms_captcha" class="form-control" placeholder="短信验证码">
            </div>
            <div class="form-group">
                <input type="text" name="username" class="form-control" placeholder="用户名" autocomplete="off">
            </div>
            <div class="form-group">
                <input type="password" name="password1" class="form-control" placeholder="密码">
            </div>
            <div class="form-group">
                <input type="password" name="password2" class="form-control" placeholder="确认密码">
            </div>
            <div class="form-group">
                <div class="input-group">
                    <input type="text" name="graph_captcha" class="form-control" placeholder="图形验证码">
                    <span class="input-group-addon captcha-addon">
                <img id="captcha-img" class="captcha-img" src="{{ url_for('common.graph_captcha') }}" alt="">
                    </span>
                </div>
            </div>
            <div class="form-group">
                <span style="display: none;" id="return-to-span">{{ return_to }}</span>
                <button id="submit-btn" class="btn btn-warning btn-block">
                    立即注册
                </button>
            </div>
{% endblock %}

templates/front/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="{{ url_for('front.signup') }}">注册</a>
</body>
</html>