apps/cms/__init__.py
from .views import bp
# from .hooks import before_request
import apps.cms.hooks

apps/cms/views.py
from flask import (
    Blueprint,
    views,
    render_template,
    request,
    session,
    redirect,
    url_for,
    g,
    jsonify
)
from .forms import (
    LoginForm,
    ResetpwdForm,
    ResetEmailForm,
    AddBannerForm,
    UpdateBannerForm,
    AddBoardForm,
    UpdateBoardForm,
)
from .models import CMSUser,CMSPersmission
from ..models import BannerModel,BoardModel,PostModel,HighlightPostModel
from .decorators import login_required,permission_requeired
import config
from exts import db,mail
from flask_mail import Message
from utils import restful,zlcache
import string
import random
from flask_paginate import Pagination,get_page_parameter
from tasks import send_mail

# 创建蓝图
# subdomain:子域名，需要做映射
bp = Blueprint("cms",__name__,url_prefix='/cms')

@bp.route('/')
@login_required
def index():
    return render_template('cms/index.html')


@bp.route('/logout/')
@login_required
def logout():
    # 清除指定会话
    # del session[config.config.CMS_USER_ID]
    # 清除所有会话
    session.clear()
    # 重定向+反转
    return redirect(url_for('cms.login'))

@bp.route('/profile/')
@login_required
def profile():
    return render_template('cms/profile.html')

@bp.route('/email_captcha/')
@login_required
def email_captcha():
    # /email_captcha/?email_capthca=xxx@qq.com
    email = request.args.get('email')
    if not email:
        return restful.params_error("请传递邮箱参数")
    # string.ascii_letters:返回a~z和A~Z的所有字母
    # 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
    source = list(string.ascii_letters)
    source.extend(map(lambda x:str(x),range(10)))
    # 随机抽取6为数
    captcha = random.sample(source,6)
    captcha = "".join([k for k in captcha])

    # 给邮箱发送邮件
    # message = Message(subject="python论坛邮箱验证码",recipients=[email],body=captcha)
    # try:
    #     mail.send(message)
    # except:
    #     return restful.params_error()
    # key:email
    # value:captch
    send_mail.delay(subject="python论坛邮箱验证码",recipients=[email],body=captcha)
    zlcache.set(email,captcha)
    return restful.success()

@bp.route('/email/')
def send_email():
    # subject:主题
    # recipients:接收者，列表类型，可以有多个接收者
    # body:发送的邮件的内容
    # sender:发送者，这个参数，可以修改发送者
    message = Message(subject='邮件发送',recipients=['1479852727@qq.com'],body='测试')
    mail.send(message)
    return "发送成功"

# 权限判断，防止跨越访问
@bp.route('/posts/')
@login_required
@permission_requeired(CMSPersmission.POSTER)
def posts():
    # posts_list = PostModel.query.all()
    page = request.args.get(get_page_parameter(),type=int,default=1)
    offset = (page-1) * config.PER_PAGE
    count = offset + config.PER_PAGE
    posts_list = PostModel.query.slice(offset,count)
    total = PostModel.query.count()
    pagination = Pagination(bs_version=3,page=page,total=total,outer_window=0,inner_window=2)
    context = {
        "posts":posts_list,
        "pagination":pagination,
    }

    return render_template('cms/posts.html',**context)

# 帖子加精
@bp.route('/hpost/',methods=['POST'])
@login_required
@permission_requeired(CMSPersmission.POSTER)
def hpost():
    post_id = request.form.get("post_id")
    if not post_id:
        return restful.params_error("请传入帖子id！")
    post = PostModel.query.get(post_id)
    if not post:
        return restful.params_error("没有这篇帖子！")
    highlight = HighlightPostModel()
    highlight.post = post
    db.session.add(highlight)
    db.session.commit()
    return restful.success()

@bp.route('/uhpost/',methods=["POST"])
@login_required
@permission_requeired(CMSPersmission.POSTER)
def uhpost():
    post_id = request.form.get("post_id")
    if not post_id:
        return restful.params_error("请传入帖子id！")
    post = PostModel.query.get(post_id)
    if not post:
        return restful.params_error("没有这篇帖子！")
    highlight = HighlightPostModel.query.filter_by(post_id=post_id).first()
    db.session.delete(highlight)
    db.session.commit()
    return restful.success()

@bp.route('/comments/')
@login_required
@permission_requeired(CMSPersmission.COMMENTER)
def comments():
    return render_template('cms/comments.html')

@bp.route('/boards/')
@login_required
@permission_requeired(CMSPersmission.BOARDER)
def boards():
    page = request.args.get(get_page_parameter(), type=int, default=1)
    offset = (page - 1) * config.PER_PAGE
    count = offset + config.PER_PAGE
    total = PostModel.query.count()
    pagination = Pagination(bs_version=3, page=page, total=total, outer_window=0, inner_window=2)
    board_models = BoardModel.query.slice(offset, count)
    context = {
        "boards":board_models,
        "pagination":pagination,
    }
    return render_template('cms/boards.html',**context)

# 添加版块
@bp.route('/aboard/',methods=['POST'])
@login_required
@permission_requeired(CMSPersmission.BOARDER)
def aboard():
    form = AddBoardForm(request.form)
    if form.validate():
        name = form.name.data
        board = BoardModel(name=name)
        db.session.add(board)
        db.session.commit()
        return restful.success()
    else:
        return restful.params_error(message=form.get_error())

# 编辑版块
@bp.route('/uboard/',methods=["POST"])
@login_required
@permission_requeired(CMSPersmission.BOARDER)
def uboard():
    form = UpdateBoardForm(request.form)
    if form.validate():
        board_id = form.board_id.data
        name = form.name.data
        board = BoardModel.query.get(board_id)
        if board:
            board.name = name
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message="没有这个版块")
    else:
        return restful.params_error(message=form.get_error())

# 删除版块
@bp.route('/dboard/',methods=["POST"])
@login_required
@permission_requeired(CMSPersmission.BOARDER)
def dboard():
    board_id = request.form.get("board_id")
    if not board_id:
        return restful.params_error(message="请传入版块id！")
    board = BoardModel.query.get(board_id)
    if not board:
        return restful.params_error(message="没有这个版块！")
    db.session.delete(board)
    db.session.commit()
    return restful.success()

@bp.route('fusers')
@login_required
@permission_requeired(CMSPersmission.FRONTUSER)
def fusers():
    return render_template('cms/fusers.html')

@bp.route('/cusers/')
@login_required
@permission_requeired(CMSPersmission.CMSUSER)
def cusers():
    return render_template('cms/cusers.html')

@bp.route('/croles/')
@login_required
@permission_requeired(CMSPersmission.ALL_PERMISSION)
def croles():
    return render_template('cms/croles.html')

@bp.route('/banners/')
@login_required
def banners():
    # banners = BannerModel.query.order_by(BannerModel.priority.desc(),BannerModel.create_time.desc()).all()
    page = request.args.get(get_page_parameter(), type=int, default=1)
    offset = (page - 1) * config.PER_PAGE
    count = offset + config.PER_PAGE
    total = BannerModel.query.count()
    pagination = Pagination(bs_version=3, page=page, total=total, outer_window=0, inner_window=2)
    banners = BannerModel.query.order_by(BannerModel.priority.desc(), BannerModel.create_time.desc()).slice(offset,count)
    context = {
        "banners":banners,
        "pagination":pagination,
    }
    return render_template('cms/banners.html',**context)

@bp.route('/abanner/',methods=['POST'])
@login_required
def abanner():
    form = AddBannerForm(request.form)
    if form.validate():
        name = form.name.data
        image_url = form.image_url.data
        link_url = form.link_url.data
        priority = form.priority.data
        banner = BannerModel(name=name,image_url=image_url,link_url=link_url,priority=priority)
        db.session.add(banner)
        db.session.commit()
        return restful.success()
    else:
        return restful.params_error(message=form.get_error())

@bp.route("/ubanner/",methods=["POST"])
@login_required
def ubanner():
    form = UpdateBannerForm(request.form)
    if form.validate():
        banner_id = form.banner_id.data
        name = form.name.data
        image_url = form.image_url.data
        link_url = form.link_url.data
        priority = form.priority.data
        banner = BannerModel.query.get(banner_id)
        if banner:
            banner.name = name
            banner.image_url = image_url
            banner.link_url = link_url
            banner.priority = priority
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message="没有这个轮播图")
    else:
        return restful.params_error(message=form.get_error())

@bp.route('/dbanner/',methods=['POST'])
@login_required
def dbanner():
    banner_id = request.form.get("banner_id")
    if not banner_id:
        return restful.params_error(message="请传入轮播图id")
    banner = BannerModel.query.get(banner_id)
    if not banner:
        return restful.params_error(message="没有这个轮播图")
    db.session.delete(banner)
    db.session.commit()
    return restful.success()

# 采用类视图,重写get|post方法
class LoginView(views.MethodView):

    def get(self,message=None):
        return render_template('cms/login.html',message=message)

    def post(self):
        # 验证表单
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            remember = form.remember.data
            user = CMSUser.query.filter_by(email=email).first()
            if user and user.check_password(password):
                session[config.CMS_USER_ID] = user.id
                if remember:
                    # 持久化
                    # 如果设置session.parmanet=True，那么过期时间是31天
                    session.permanent = True
                # 反转蓝图规则:蓝图名.视图
                return redirect(url_for('cms.index'))
            else:
                return self.get(message="邮箱或密码错误")
        else:
            # print(form.errors)
            message = form.get_error()
            return self.get(message=message)

class ResetPwdView(views.MethodView):

    # 给类视图定义装饰器
    decorators = [login_required]

    def get(self):

apps/front/views.py
from flask import (
    Blueprint,
    views,
    render_template,
    request,
    session,
    url_for,
    g,
    abort
)
from .forms import SignupForm,SigninForm,AddPostForm,AddCommentForm
from utils import restful,safeutils
from .models import FrontUser
from ..models import BoardModel,BannerModel,PostModel,CommentModel,HighlightPostModel,LikePostModel
from exts import db
import config
from .decorators import login_required
# from exts import alidayu
from flask_paginate import Pagination,get_page_parameter
from sqlalchemy.sql import func

bp = Blueprint("front",__name__)

@bp.route('/')
def index():
    sort = request.args.get("st",type=int,default=1) # 排序
    board_id = request.args.get("board_id",type=int,default=None)
    boards = BoardModel.query.all()
    banners = BannerModel.query.order_by(BannerModel.priority.desc(),BannerModel.create_time.desc()).limit(4)
    # posts = PostModel.query.all()
    page = request.args.get(get_page_parameter(),type=int,default=1)
    offset = (page-1) * config.PER_PAGE
    count = offset + config.PER_PAGE
    # 从第几条开始显示第end条数据
    # posts = PostModel.query.slice(offset,count)
    posts = None
    total = 0
    query_obj = None

    if sort == 1:
        # 最新
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 2:
        # 按加精时间倒序排序
        # 两个表连接查询需要使用db.session()
        query_obj = db.session.query(PostModel).outerjoin(HighlightPostModel).order_by(HighlightPostModel.create_time.desc(),PostModel.create_time.desc())
    elif sort == 3:
        # 按照点赞数量排序
        query_obj = db.session.query(PostModel).outerjoin(LikePostModel).order_by(LikePostModel.like_num.desc(),PostModel.create_time.desc())
    elif sort == 4:
        query_obj = db.session.query(PostModel).outerjoin(CommentModel).group_by(PostModel.id).order_by(func.count(CommentModel.id).desc(),PostModel.create_time.desc())

    if board_id:
        # 按照版块筛选
        query_obj = PostModel.query.filter(PostModel.board_id==board_id)
        posts = query_obj.slice(offset,count)
        total = query_obj.count()
    else:
        posts = query_obj.slice(offset,count)
        total = query_obj.count()
    # 传入页数参数，数据的总条数
    pagination = Pagination(bs_version=3,page=page,total=total,outer_window=0,inner_window=2)
    context = {
        "boards":boards,
        "banners":banners,
        'posts':posts,
        'pagination':pagination,
        'current_board':board_id,
        'current_sort':sort,
        'like_obj':db.session.query(LikePostModel).outerjoin(PostModel),
    }
    return render_template("front/index.html",**context)

@bp.route('/<name>/<post_id>/')
def post_detail(name,post_id):
    post = PostModel.query.get(post_id)
    like = db.session.query(LikePostModel).outerjoin(PostModel).filter(PostModel.id == post_id).first()
    if not post:
        abort(404)
    return render_template('front/pdetail.html',post=post,like=like)

@bp.route('/acomment/',methods=["POST"])
@login_required
def add_comment():
    form = AddCommentForm(request.form)
    if form.validate():
        content = form.content.data
        # 通过帖子id，判断是否有当前帖子
        post_id = form.post_id.data
        post = PostModel.query.get(post_id)
        if post:
            comment = CommentModel(content=content)
            comment.post = post
            comment.author = g.front_user
            db.session.add(comment)
            db.session.commit()
            return restful.success()
        else:
            return  restful.params_error("没有这篇帖子！")
    else:
        return restful.params_error(form.get_error())

@bp.route('/apost/',methods=['GET','POST'])
@login_required
def apost():
    if request.method == "GET":
        boards = BoardModel.query.all()
        return render_template('front/apost.html',boards=boards)
    else:
        form = AddPostForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            board_id = form.board_id.data
            board = BoardModel.query.get(board_id)
            if not board:
                return restful.params_error(message="没有这个模块！")
            post = PostModel(title=title,content=content)
            post.board = board
            post.author = g.front_user
            db.session.add(post)
            db.session.commit()
            return  restful.success()
        else:
            return restful.params_error(message=form.get_error())

@bp.route('/alike/')
def add_like():
    post_id = request.args.get("post_id")
    post = PostModel.query.get(post_id)
    if not post:
        return restful.params_error("没有这篇帖子！")
    like = db.session.query(LikePostModel).outerjoin(PostModel).filter(PostModel.id==post_id).first()
    if like:
        like_num = like.like_num
    else:
        like = LikePostModel(like_num=0)
        like.post = post
        like_num = 0
    like_num = like_num+1
    print(like_num)
    like.like_num = like_num
    db.session.commit()
    return restful.success()

class SignupView(views.MethodView):

    def get(self):
        return_to = request.referrer
        print(return_to)
        if return_to and return_to != request.url and safeutils.is_safe_url(return_to):
            return render_template('front/signup.html',return_to=return_to)
        else:
            return render_template('front/signup.html')

    def post(self):
        form = SignupForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            username = form.username.data
            password = form.password1.data
            user = FrontUser(telephone=telephone,username=username,password=password)
            db.session.add(user)
            db.session.commit()
            return restful.success()
        else:
            # print(form.get_error())
            return restful.params_error(message=form.get_error())

class SigninView(views.MethodView):

    def get(self):
        return_to = request.referrer
        if return_to and return_to != request.url and return_to != url_for("front.signup") and safeutils.is_safe_url(return_to):
             return render_template("front/signin.html",return_to=return_to)
        else:
             return render_template('front/signin.html')

    def post(self):
        form = SigninForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            password = form.password.data
            remember = form.remeber.data
            # 检索是否拥有这个账号
            user = FrontUser.query.filter_by(telephone=telephone).first()
            if user and user.check_password(password):
                session[config.FRONT_USER_ID] = user.id
                if remember:
                    session.permanent = True
                return restful.success()
            else:
                return restful.params_error(message="手机号码或者密码错误")
        else:
            return restful.params_error(message=form.get_error())


bp.add_url_rule(rule='/signup/',view_func=SignupView.as_view('signup'))
bp.add_url_rule(rule='/signin/',view_func=SigninView.as_view('signin'))

templates/cms/banners.html
{% extends 'cms/base.html' %}

{% block title %}
    轮播图管理
{% endblock %}

{% block head %}
    <script src="https://cdn.staticfile.org/Plupload/2.1.1/moxie.js"></script>
    <script src="https://cdn.staticfile.org/Plupload/2.1.1/plupload.dev.js"></script>
    <script src="https://cdn.staticfile.org/qiniu-js-sdk/1.0.14-beta/qiniu.js"></script>
    <script src="{{ url_for('static',filename="cms/js/banners.js") }}"></script>
    <script src="{{ url_for('static',filename="common/zlqiniu.js") }}"></script>
    <style>
        .top-box button {
            float: right;
        }
    </style>
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    <div class="top-box">
        <button class="btn btn-warning" data-toggle="modal" data-target="#banner-dialog">
            添加轮播图
        </button>
    </div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>名称</th>
            <th>图片链接</th>
            <th>跳转链接</th>
            <th>优先级</th>
            <th>创建时间</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for banner in banners %}
            <tr data-name="{{ banner.name }}" data-image="{{ banner.image_url }}" data-link="{{ banner.link_url }}"
                data-priority="{{ banner.priority }}" data-id="{{ banner.id }}">
                <td>{{ banner.name }}</td>
                <td><a href="{{ banner.image_url }}" target="_blank">{{ banner.image_url }}</a></td>
                <td><a href="{{ banner.link_url }}" target="_blank">{{ banner.link_url }}</a></td>
                <td>{{ banner.priority }}</td>
                <td>{{ banner.create_time }}</td>
                <td>
                    <button class="btn btn-default btn-xs edit-banner-btn">编辑</button>
                    <button class="btn btn-danger btn-xs delete-banner-btn">删除</button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
        </div>
    </table>
    <div style="text-align: center;">
        {{ pagination.links }}
    </div>

    <!-- Modal -->
    <div class="modal fade" id="banner-dialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">轮播图</h4>
                </div>
                <div class="modal-body">
                    <form action="" method="post" class="form-horizontal" autocomplete="off">
                        <div class="form-group">
                            <label class="col-sm-2 control-label">名称:</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="name" placeholder="轮播图名称">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">图片:</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control" name="image_url" placeholder="轮播图图片">
                            </div>
                            <button class="btn btn-info col-sm-2" id="upload-btn">
                                添加图片
                            </button>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">跳转:</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="link_url" placeholder="跳转链接">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">权重:</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="priority" placeholder="优先级(请输入0~10的数字)">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                    <button id="save-banner-btn" type="button" class="btn btn-primary">保存</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/cms/base.html
{% from "common/_macros.html" import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Pragma" content="no-cache"/>
    <meta http-equiv="Cache-Control" content="no-cache"/>
    <meta http-equiv="Expires" content="0"/>
    <title>{% block title %}{% endblock %}</title>
    {% include "common/_heads.html" %}
    <script src="http://cdn.bootcss.com/blueimp-md5/2.10.0/js/md5.min.js"></script>
    <link rel="stylesheet" href="{{ static('cms/css/base.css') }}">
    <script src="{{ static('cms/js/base.js') }}"></script>
    {% block head %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">课堂论坛CMS管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{{ url_for('cms.profile') }}">{{ g.cms_user.username }}<span></span></a></li>
                <li><a href="{{ url_for('cms.logout') }}">注销</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="查找...">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav-sidebar">
                <li class="unfold"><a href="{{ url_for('cms.index') }}">首页</a></li>
                <li class="profile-li">
                    <a href="#">个人中心<span></span></a>
                    <ul class="subnav">
                        <li><a href="{{ url_for('cms.profile') }}">个人信息</a></li>
                        <li><a href="{{ url_for("cms.resetpwd") }}">修改密码</a></li>
                        <li><a href="{{ url_for('cms.resetemail') }}">修改邮箱</a></li>
                    </ul>
                </li>

                {% set cms_user = g.cms_user %}
                <li class="nav-group banner-manage"><a href="{{ url_for('cms.banners') }}">轮播图管理</a></li>
                {% if cms_user.has_permission(CMSPersmission.POSTER) %}
                    <li class="nav-group post-manage"><a href="{{ url_for('cms.posts') }}">帖子管理</a></li>
                {% endif %}

                {% if cms_user.has_permission(CMSPersmission.COMMENTER) %}
                    <li class="comments-manage"><a href="{{ url_for('cms.comments') }}">评论管理</a></li>
                {% endif %}

                {% if cms_user.has_permission(CMSPersmission.BOARDER) %}
                    <li class="board-manage"><a href="{{ url_for('cms.boards') }}">板块管理</a></li>
                {% endif %}

                {% if cms_user.has_permission(CMSPersmission.FRONTUSER) %}
                    <li class="nav-group user-manage"><a href="{{ url_for('cms.fusers') }}">前台用户管理</a></li>
                {% endif %}

                {% if cms_user.has_permission(CMSPersmission.CMSUSER) %}
                    <li class="nav-group cmsuser-manage"><a href="{{ url_for('cms.cusers') }}">CMS用户管理</a></li>
                {% endif %}

                {% if cms_user.is_developer %}
                    <li class="cmsrole-manage"><a href="{{ url_for('cms.croles') }}">CMS组管理</a></li>
                {% endif %}


            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1>{% block page_title %}{% endblock %}</h1>
            <div class="main_content">
                {% block main_content %}{% endblock %}
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/cms/boards.html
{% extends 'cms/base.html' %}

{% block title %}
    版块管理
{% endblock %}

{% block head %}
    <script src="{{ url_for('static',filename='cms/js/boards.js') }}"></script>
{% endblock %}

{% block page_title %}
    {{  self.title() }}
{% endblock %}

{% block main_content %}
    <div class="top-box">
        <button class="btn btn-warning" style="float:right" id="add-board-btn">添加新版块</button>
    </div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>版块名称</th>
                <th>帖子数量</th>
                <th>创建时间</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            {% for board in boards %}
                <tr data-name="{{ board.name }}" data-id="{{ board.id }}">
                    <td>{{ board.name }}</td>
                    <td>0</td>
                    <td>{{ board.create_time }}</td>
                    <td>
                        <button class="btn btn-default btn-xs edit-board-btn">编辑</button>
                        <button class="btn btn-danger btn-xs delete-board-btn">删除</button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div style="text-align: center;">
        {{ pagination.links }}
    </div>
{% endblock %}

templates/cms/comments.html
{% extends 'cms/base.html' %}

{% block title %}
    评论管理
{% endblock %}

{% block head %}
    
{% endblock %}

{% block page_title %}
    {{  self.title() }}
{% endblock %}

{% block main_content %}
    评论管理页面
{% endblock %}

templates/cms/croles.html
{% extends 'cms/base.html' %}

{% block title %}
    CMS角色管理
{% endblock %}

{% block head %}
    
{% endblock %}

{% block page_title %}
    {{  self.title() }}
{% endblock %}

{% block main_content %}
    CMS角色管理页面
{% endblock %}

templates/cms/cusers.html
{% extends 'cms/base.html' %}

{% block title %}
    CMS用户管理
{% endblock %}

{% block head %}
    
{% endblock %}

{% block page_title %}
    {{  self.title() }}
{% endblock %}

{% block main_content %}
    CMS用户管理页面
{% endblock %}

templates/cms/fusers.html
{% extends 'cms/base.html' %}

{% block title %}
    前台用户管理
{% endblock %}

{% block head %}
    
{% endblock %}

{% block page_title %}
    {{  self.title() }}
{% endblock %}

{% block main_content %}
    前台用户管理页面
{% endblock %}

templates/cms/index.html
{% extends 'cms/base.html' %}

{% block title %}
    CMS管理系统
{% endblock %}

{% block page_title %}
    欢迎来到CMS管理系统
{% endblock %}

templates/cms/posts.html
{% extends 'cms/base.html' %}
{% from "common/_macros.html" import static %}

{% block title %}
    帖子管理
{% endblock %}

{% block head %}
    <script src="{{ static("cms/js/posts.js") }}"></script>
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>标题</th>
            <th>发布时间</th>
            <th>模块</th>
            <th>作者</th>
            <th>操作</th>
        </thead>
        <tbody>
        {% for post in posts %}
            <tr data-id="{{ post.id }}" data-highlight="{{ 1 if post.highlight else 0 }}">
                <td>
                    <a target="_blank" href="{{ url_for("front.post_detail",name=post.author.username,post_id=post.id) }}">{{ post.title }}</a>
                </td>
                <td>{{ post.create_time }}</td>
                <td>{{ post.board.name }}</td>
                <td>{{ post.author.username }}</td>
                <td>
                    {% if  post.highlight %}
                        <button class="btn btn-warning btn-xs highlight-btn" >取消加精</button>
                    {% else %}
                        <button class="btn btn-default btn-xs highlight-btn">加精</button>
                    {% endif %}
                        <button class="btn btn-danger btn-xs">移除</button>

                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div style="text-align: center;">
        {{ pagination.links }}
    </div>
{% endblock %}